version: "3.8"

services:

  spring-app:
    image: spring-app
    build: ./
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - server.servlet.context-path=/kaddem
      - spring.datasource.url="jdbc:mysql://db-mysql:3306/kaddemdb?createDatabaseIfNotExist=true"
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - logging.level.com.zaxxer.hikari=INFO
      - logging.level.org.springframework=INFO
      - logging.level.root=INFO
      - logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n"


    volumes:
      - .m2:/root/.m2
    stdin_open: true
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:8
    restart: unless-stopped
  ##  env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddemdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"



volumes:
  db: